---
language: python

dist: trusty

python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: 3.6-dev
    - python: 3.7-dev
    - python: nightly

install:
  - pip install -r requirements/dev.txt
  - pip install codacy-coverage

script:
  - python -m pytest --cov=tor_api

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml